### ISSUE TITLE
feature: add readUTFBytes(length: number): string

### ISSUE THREAD

**Issue by Gi-jutsu** [Call-Me-Dev/byte-array#18]
# Description

Implement the ```readUTFBytes(length: number): string``` method.
see: https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/utils/ByteArray.html#readUTFBytes()

# ToDo
- [x] Add ```readUTFBytes(length: number): string```
- [x] Add unitary specs
- [x] Update the unitary specs of writeUTFBytes
